Repository google/robotstxt, pull requests merged in 2019-07, with the labels that each got.

#15 Early return
  robots.cc
Labels: enhancement

#4 Added support to build project with CMake
  .gitignore
  CMakeLists.txt
  CMakeLists.txt.in
  README.md
Labels: cla: yes, enhancement

#24 fix typo: the target name is test
  README.md
Labels: cla: yes, documentation
